### ISSUE TITLE
Incompatible with raysect>=0.6.0

### ISSUE THREAD

**Issue by TomFarley** [cherab/solps#12]
Raysect has been refactored in version 0.6.0 with Discrete2DMesh moved from raysect.core.math.interpolators to raysect.core.math.function. This has broken the solps cherab module in its current form.

Attempting to install the solps module results in a number of errors starting with:

tfarley@freia013:~/repos/cherab/solps$ python setup.py install --user
Compiling cherab/solps/solps_3d_functions.pyx because it changed.
[1/1] Cythonizing cherab/solps/solps_3d_functions.pyx
Error compiling Cython file:
------------------------------------------------------------
...
from libc.math cimport atan2, M_PI
import numpy as np
from numpy cimport ndarray

from raysect.core.math.vector cimport Vector3D, new_vector3d
from raysect.core.math.interpolators cimport Discrete2DMesh
^
------------------------------------------------------------
cherab/solps/solps_3d_functions.pyx:26:0: 'raysect/core/math/interpolators.pxd' not found

**Comment by jacklovell** [comment]
Thanks Tom. We'd made this change upstream in Cherab, but not in the SOLPS package. I've just pushed the fix to the development branch: can you try running from that?

**Comment by TomFarley** [comment]
Brilliant, that's fixed it, thanks Jack.

**Comment by jacklovell** [comment]
Closed by #13
