### ISSUE TITLE
Add class functions returning data interpolators to SOLPSSimulation

### ISSUE THREAD

**Issue by Mateasek** [cherab/solps#20]
I think it would be a nice addition to the SOLPSSimulation. The interpolators are created within the create_plasma function. Moving the code to separate funcions would add a nice possibility to use the solps module for plotting, data generation and etc. together with cherab samplers.

For such purposes functions returning 2D interpolators would be enough, but adding functions returning 3D interpolators shouldn't harm anyone. I would be happy to do this.

**Comment by vsnever** [comment]
Just would like to point out that there is one not obvious advantage of `SOLPSFunction3D` over the `AxisymmetricMapper(Discrete2DMesh())` approach. `SOLPSFunction3D` uses a pointer to the original data on the SOLPS grid, while `Discrete2DMesh()` copies the data on the triangular mesh on initialisation. So, in case of  `SOLPSFunction3D`, if the original data is manually modified by the user (for example to correct some bad data points), the interpolator does not need to be reinitialised.
