### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jacklovell** [cherab/solps#21]
The current master branch of cherab-solps is incompatible with the released versions of raysect and cherab-core. This means new users need to check out the development branch before installing, which has led to confusion in a number of cases. There have been recent proposals to re-architect parts of this repository (e.g. input file reading), so I think it makes sense to make a new release of the current code before large scale changes are made.

For the release, I think the following is required (updated with additional suggestions):

- [x] Update Changelog.
- [x] Bump version number (1.1.0?)
- [x] Flesh out README with some installation instructions, including the need to use Cython 3.0a instead of 0.29.x for a reliable installation. See https://github.com/cherab/Soledge2D/blob/development/README.md for what I had in mind.
- [ ] Self-contained demo with example SOLPS output files.

@mattngc @CnlPepper do you agree with this?

**Comment by mattngc** [comment]
All of that sounds fine to me. Also, I think you need to consider adding a demonstration case to this module. Something like the demo Vlad is contributing to core. An obvious issue might be the raw file size, but if you can get agreement from the owners and just contribute a minority of files instead of the full case, it might allow a self contained example of module use. Like other parts of Cherab, I believe the biggest barrier to use is often the lack of the required source data.

If Vlad's case is going into core anyway (custom format though) you may be able to get a few raw files from that same case.

**Comment by jacklovell** [comment]
Yes, good point. We already have an MDSplus demo, which is self-contained in the sense that it can be run with no additional files. It does require read access to the SOLPS MDSplus server, but if a user doesn't have that then a demonstration of its functionality isn't going to be much use to them anyway.

Vlad's example would fit nicely as a raw files demo. I'll see if he can provide the original SOLPS output files for it.

**Comment by mattngc** [comment]
Also, the requirements for it to be used here will be the same as in the core issue. The case itself looks good, it's just waiting for the equilibrium object to be fixed. If you manage to solve that here it will solve both issues.

**Comment by Mateasek** [comment]
What is the status of this issue? Have you had any time to look into it @jacklovell ? Would it be possible to skip (for now) the self-contained demo, if it is the reason why the new release hasn't been pushed yet? It would be nice to have the development branch updated so it is compatible with the current raysect and cherab development branches, after the changes in the function framework.

**Comment by Mateasek** [comment]
Meanwhile I could make a branch and update the code to be compatible with the new function framework, if @jacklovell agrees.

**Comment by jacklovell** [comment]
Yes, the self-contained demo is holding this up: the simulation proposed in https://github.com/cherab/core/issues/211#issuecomment-594231679 was done in an older version of SOLPS which doesn't output the B2 files required for cherab-solps. And I *really* don't want to have to deal with yet another poorly-documented format in this codebase.

The pragmatic approach would be to deal with the first 3 items on the list, make a release and defer the self-contained example to a later release.

The most pressing issue we have is that cherab-solps master is not compatible with raysect and cherab-core master (i.e. the released versions on PyPI) and cherab-solps development is no longer compatible with raysect and cherab-core development. I'll put out a release today to fix the first of these, so at least we can have a "cherab-stable" software stack for end users to use which will just work. Then we can update solps-development for compatibility with raysect and core development and go from there. I already have a local branch for this, so I'll push that up too.

**Comment by Mateasek** [comment]
Thanks @jacklovell, let me know if you need any help.

**Comment by jacklovell** [comment]
I've opened #30 to track the creation of a self-contained example. It shouldn't hold up this release any longer, but it also shouldn't be forgotten about.

**Comment by jacklovell** [comment]
@Mateasek I've just pushed [a new branch](/cherab/solps/tree/maintenance/raysect-imports) which has compatibility with the current development branches of raysect and Cherab-core.
