### ISSUE TITLE
Error reading MAST-U MDSplus simulation

### ISSUE THREAD

**Issue by jacklovell** [cherab/solps#22]
When reading a MAST-U simulation, number 121844, from the `solps-mdsplus.aug.ipp.mpg.de:8001` MDSplus server I get the following error:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/Cherab/cherab_solps/demos/mastu_solps_from_mdsplus.py in <module>
     33 
     34 
---> 35 sim = load_solps_from_mdsplus(mds_server, ref_number)
     36 plasma = sim.create_plasma()
     37 mesh = sim.mesh

~/Cherab/cherab_solps/cherab/solps/formats/mdsplus.py in load_solps_from_mdsplus(mds_server, ref_number)
    180     for i in range(ni):
    181         for j in range(nj):
--> 182             total_rad_data[i, j] = (linerad[i, j] + brmrad[i, j] + neurad[i, j]) / vol[i, j]
    183     sim._total_rad = total_rad_data
    184 

IndexError: index 3 is out of bounds for axis 1 with size 3
```
This particular simulation has an ENEUTRAD value with shape (3, 34, 148), in contrast to the 69636 in the demo file which is of shape (34, 148). The radiation is resolved into 3 different neutral species.

It looks like the sum over strata is using the wrong axis. This behaviour started with commit 00bb489cbd9ede0a07e6b601948be2d71274834f, and from what I can make out this commit changed the behaviour compared with previous behaviour. This doesn't make sense to me though, as it would be a breaking change.

The error above is easily resolved by changing the axis over which ENEUTRAD is summed, from 2 to 0. But I'm nervous about making this change, as it could break the routine for reference numbers which work with the existing code.

@mattngc can you remember back to when this change was made, and whether there are any test cases with multiple strata which work with the existing code? Otherwise I'll make my proposed change and consider it a bugfix.

**Comment by mattngc** [comment]
Hey Jack, no unfortunately I don't remember. It's likely I was trying to get a particular case to work at the time. It does look like a bug. No problems with making the change on my side.
