### ISSUE TITLE
Compatibility with Cherab 1.4.0

### ISSUE THREAD

**Issue by jacklovell** [cherab/solps#69]
Now that Cherab 1.4.0 has been released, I've been checking compatibility with the other submodules. Most seem to be fine, but cherab-solps has cherab==1.3 specified as both a build requirement and an installation requirement. I've tested cherab-solps 1.2.0 with cherab-core 1.4.0, and all (6) unit tests pass and most of the demos seem to run OK, except for a couple of things:

* Warnings about possible binary incompatibility due to some of the core LineShape classes changing size.
* The `generomak_raw_files_solps_line_emitter.py` demo fails with `AttributeError: 'FibreOpticGroup' object has no attribute 'add_sight_line'`

I propose making a new point release of cherab-solps, 1.2.1, where the only changes made are for compatibility with cherab 1.4.0. That way users of cherab-solps can benefit from the latest core release without having to wait for new features to be added to cherab-solps to warrant a new minor release.

@vsnever @Mateasek thoughts?

**Comment by vsnever** [comment]
I agree. In `generomak_raw_files_solps_line_emitter.py` we just need to use the new implementation of the group observers introduced in Cherab 1.4. I'll update the demo and make a PR.

**Comment by jacklovell** [comment]
Great, thanks!
