### ISSUE TITLE
SOLPS rewrite and tidy-up

### ISSUE THREAD

**Issue by CnlPepper** [cherab/solps#8]
There is a lot of bad code in this package that really needs addressing. At present the SOPLS sim object has no way of being initialised without modifying internal, hidden attributes. I've spotted a few cases of API inconsistency and incorrect docstrings.

**Comment by mattngc** [comment]
To be honest, we need a new maintainer for this module. I might post it somewhere. I wrote this module 3+ years ago and have barely worked on it since. Ideally we should find a SOLPS developer or heavy user to look after it.

**Comment by vsnever** [comment]
I think `SOLPSSimulation` class should be initialised with `mesh, species_list` instead of just `mesh`, because this will allow to define property setters that check array dimensions.

**Comment by vsnever** [comment]
Is is safe to remove `parallel_velocities` and `radial_velocities` attributes from `SOLPSSimulation`? Seems like duplicates to `velocities_parallel` and `velocities_radial`.
